name: Demo Checker

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时执行一次

jobs:
  clash-proxy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install requests
          pip install PyYAML
          pip install tqdm

      - name: Run script
        run: |
          python main.py

      - name: Add proxies directory
        run: |
          mkdir -p assets/proxies
          cp ./docs/result.yaml assets/proxies
        working-directory: ./docs

      - name: Debug
        run: |
          echo "Current working directory: $(pwd)"
          echo "Files in current directory: $(ls -al)"
        working-directory: ./docs/assets/proxies

      - name: Commit result
        run: |
          git config --global user.email "corotata@gmail.com"
          git config --global user.name "corotata"
          git checkout gh-pages
          git add .
          git commit -m "Update result"
          git push origin gh-pages
